dependencies:
  - bertviz==1.2.0
  - datasets==1.16.1
  - encoder==1.1
  - ftfy==6.1.3
  - huggingface_hub==0.20.3
  - ipython==8.21.0
  - ipywidgets==8.1.1
  - matplotlib==3.8.2
  - networkx==3.2.1
  - nltk==3.6.6
  - numpy==1.26.4
  - openai==1.12.0
  - pandas==2.2.0
  - Pillow==10.2.0
  - pytest==8.0.0
  - regex==2023.12.25
  - Requests==2.31.0
  - sample==1.0.0
  - scipy==1.12.0
  - setuptools==69.0.2
  - spacy==3.7.2
  - tensorflow==2.15.0
  - termcolor==2.4.0
  - toposort==1.10
  - torch==2.2.0
  - torchtext==0.6.0
  - torchvision==0.17.0
  - tqdm==4.66.1
  - transformers==4.16.2
  - watermark==2.4.3
